# Generated by Django 3.2.15 on 2025-05-27 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('request_data', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата получения геоданных')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
