# Generated by Django 3.2.15 on 2025-05-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('underway', 'В работе'), ('delivery', 'Доставка'), ('completed', 'Завершен')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
