# Generated by Django 3.2.15 on 2025-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20250523_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличный'), ('non_cash', 'Безналичный')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('underway', 'В работе'), ('delivery', 'Доставка'), ('completed', 'Завершен')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус'),
        ),
    ]
