services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../static:/static
    command: sh -lc "cp -r /app/static/bundles/* /static/"

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ../db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  backend-collectstatic:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ../static:/static
    command: >
      bash -lc "python manage.py collectstatic --noinput && cp -r /app/static/* /static/"
    depends_on:
      - db

  backend-migrate:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    command: >
      bash -lc "python manage.py migrate --noinput"
    depends_on:
    - db

  web:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../media:/app/media:rw
      - ../static:/app/static:ro
    ports:
      - "8000:8000"
    command: >
      gunicorn star_burger.wsgi:application
      --bind 0.0.0.0:8000
    depends_on:
      - db
      - frontend
      - backend-collectstatic
      - backend-migrate

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../static:/var/www/static:ro
      - ../media:/var/www/media:ro
    depends_on:
      - web

