services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../static:/static
    command: sh -lc "cp -r /app/static/bundles/* /static/"

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ../db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  backend-collectstatic:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    volumes:
      - ../static:/static
    command: sh -lc "cp -r /app/static/* /static/"

  backend-migrate:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    command: >
          bash -lc "python manage.py migrate --noinput"
    depends_on:
      - db

  web:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../media:/app/media:rw
      - ../static:/app/static:ro
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      gunicorn star_burger.wsgi:application
      --bind 0.0.0.0:8000
    depends_on:
      - db
      - frontend
      - backend-collectstatic
      - backend-migrate

